/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ImageSearch_CONSTANTS_H
#define ImageSearch_CONSTANTS_H

#include "ImageSearch_types.h"

namespace ImgMatch {

class ImageSearchConstants {
 public:
  ImageSearchConstants();

};

extern const ImageSearchConstants g_ImageSearch_constants;

} // namespace

#endif
